# Generated by Django 6.0 on 2026-01-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='addree_line1',
            new_name='address_line1',
        ),
    ]
